AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/LineLength:
  Max: 130

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'

Metrics/MethodLength:
  Max: 30

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/StringLiterals:
  Enabled: false

